### ISSUE TITLE
Seems not to run with Zulu Java 11

### ISSUE THREAD

**Issue by schrej-zz** [GollmerSt/SolvisSmartHomeServer#9]
I don't get the program to run with Java Zulu 11.
Log entry: 
`[2022-04-03 16:52:38,208] ERROR de.sgollmer.solvismax.model.SolvisWorkers - Error was thrown in measurements worker thread. Cause: : java.lang.NullPointerException
	at de.sgollmer.solvismax.model.objects.ErrorDetection$WriteErrorScreens.update(ErrorDetection.java:382)
	at de.sgollmer.solvismax.model.objects.ErrorDetection$WriteErrorScreens.update(ErrorDetection.java:358)
	at de.sgollmer.solvismax.model.objects.Observer$Observable.notify(Observer.java:44)
	at de.sgollmer.solvismax.model.Solvis.notifySolvisErrorObserver(Solvis.java:375)
	at de.sgollmer.solvismax.model.SolvisState.processError(SolvisState.java:147)
	at de.sgollmer.solvismax.model.SolvisState.setError(SolvisState.java:76)
	at de.sgollmer.solvismax.model.objects.ErrorDetection$Execute.update(ErrorDetection.java:350)
	at de.sgollmer.solvismax.model.objects.ErrorDetection$Execute.update(ErrorDetection.java:321)
	at de.sgollmer.solvismax.model.objects.Observer$Observable.notify(Observer.java:44)
	at de.sgollmer.solvismax.model.objects.data.SolvisData.setData(SolvisData.java:166)
	at de.sgollmer.solvismax.model.objects.data.SolvisData.setData(SolvisData.java:109)
	at de.sgollmer.solvismax.model.objects.data.SolvisData.setBoolean(SolvisData.java:238)
	at de.sgollmer.solvismax.model.objects.measure.Strategy$Boolean.get(Strategy.java:140)
	at de.sgollmer.solvismax.model.objects.measure.Strategy.get(Strategy.java:37)
	at de.sgollmer.solvismax.model.objects.measure.Measurement.getValue(Measurement.java:124)
	at de.sgollmer.solvismax.model.objects.ChannelDescription.getValue(ChannelDescription.java:87)
	at de.sgollmer.solvismax.model.objects.ChannelDescription.getValue(ChannelDescription.java:81)
	at de.sgollmer.solvismax.model.objects.AllChannelDescriptions.measure(AllChannelDescriptions.java:148)
	at de.sgollmer.solvismax.model.Solvis.measure(Solvis.java:294)
	at de.sgollmer.solvismax.model.SolvisWorkers$MeasurementsWorkerThread.run(SolvisWorkers.java:494)`

**Comment by GollmerSt** [comment]
The issue is solved?

**Comment by GollmerSt** [comment]
I don't quite get it. Is there a problem that can be solved with the Makefile?
I'd really like to provoke the error, because there should be a better error message than a null pointer exception.
